name: my-tests
on:
  - push
env:
   CI: true
jobs: 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - run: make install
      - run: make lint
      - run: make test